CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),email text NOT NULL UNIQUE CHECK(email=lower(email)),name text NOT NULL,password_hash text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE sessions(token_hash text PRIMARY KEY,user_id uuid NOT NULL REFERENCES users ON DELETE CASCADE,expires_at timestamptz NOT NULL);
CREATE INDEX sessions_expiry ON sessions(expires_at);
CREATE TABLE rate_limits(key text PRIMARY KEY,count integer NOT NULL,expires_at timestamptz NOT NULL);
CREATE TABLE workspaces(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,issue_counter integer NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE members(workspace_id uuid REFERENCES workspaces ON DELETE CASCADE,user_id uuid REFERENCES users ON DELETE CASCADE,role text NOT NULL CHECK(role IN ('owner','admin','member','viewer')),PRIMARY KEY(workspace_id,user_id));
CREATE INDEX members_user ON members(user_id);
CREATE TABLE invitations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id uuid NOT NULL REFERENCES workspaces ON DELETE CASCADE,email text NOT NULL,role text NOT NULL CHECK(role IN ('admin','member','viewer')),token_hash text NOT NULL UNIQUE,expires_at timestamptz NOT NULL,accepted_at timestamptz);
CREATE TABLE projects(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id uuid NOT NULL REFERENCES workspaces ON DELETE CASCADE,name text NOT NULL,key text NOT NULL,description text NOT NULL DEFAULT '',archived boolean NOT NULL DEFAULT false,UNIQUE(workspace_id,key),UNIQUE(workspace_id,id));
CREATE TABLE project_members(workspace_id uuid NOT NULL,project_id uuid NOT NULL,user_id uuid NOT NULL,PRIMARY KEY(project_id,user_id),FOREIGN KEY(workspace_id,project_id) REFERENCES projects(workspace_id,id) ON DELETE CASCADE,FOREIGN KEY(workspace_id,user_id) REFERENCES members ON DELETE CASCADE);
CREATE TABLE issues(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id uuid NOT NULL REFERENCES workspaces ON DELETE CASCADE,project_id uuid NOT NULL,number integer NOT NULL,title text NOT NULL CHECK(length(title) BETWEEN 1 AND 240),description text NOT NULL DEFAULT '',status text NOT NULL CHECK(status IN ('backlog','todo','in-progress','in-review','done')),priority text NOT NULL CHECK(priority IN ('urgent','high','medium','low','none')),assignee_id uuid,reporter_id uuid NOT NULL REFERENCES users,labels text[] NOT NULL DEFAULT '{}',due_date date,version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(workspace_id,number),UNIQUE(workspace_id,id),FOREIGN KEY(workspace_id,project_id) REFERENCES projects(workspace_id,id),FOREIGN KEY(workspace_id,assignee_id) REFERENCES members(workspace_id,user_id));
CREATE INDEX issues_page ON issues(workspace_id,created_at DESC,id DESC);
CREATE INDEX issues_status ON issues(workspace_id,status,created_at DESC,id DESC);
CREATE INDEX issues_project ON issues(workspace_id,project_id,created_at DESC,id DESC);
CREATE INDEX issues_assignee ON issues(workspace_id,assignee_id);
CREATE INDEX issues_due ON issues(workspace_id,due_date);
CREATE INDEX issues_labels ON issues USING gin(labels);
CREATE INDEX issues_search ON issues USING gin(to_tsvector('english',title||' '||description));
CREATE TABLE comments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id uuid NOT NULL,issue_id uuid NOT NULL,author_id uuid NOT NULL REFERENCES users,body text NOT NULL CHECK(length(body) BETWEEN 1 AND 10000),created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(workspace_id,issue_id) REFERENCES issues(workspace_id,id) ON DELETE CASCADE);
CREATE INDEX comments_page ON comments(issue_id,created_at DESC,id DESC);
CREATE TABLE watchers(workspace_id uuid NOT NULL,issue_id uuid NOT NULL,user_id uuid NOT NULL,PRIMARY KEY(issue_id,user_id),FOREIGN KEY(workspace_id,issue_id) REFERENCES issues(workspace_id,id) ON DELETE CASCADE,FOREIGN KEY(workspace_id,user_id) REFERENCES members ON DELETE CASCADE);
CREATE TABLE attachments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id uuid NOT NULL,issue_id uuid NOT NULL,name text NOT NULL,mime text NOT NULL,size integer NOT NULL CHECK(size<=5242880),content bytea NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(workspace_id,issue_id) REFERENCES issues(workspace_id,id) ON DELETE CASCADE);
CREATE INDEX attachments_issue ON attachments(issue_id);
CREATE TABLE activity(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,workspace_id uuid NOT NULL REFERENCES workspaces ON DELETE CASCADE,project_id uuid,issue_id uuid,actor_id uuid REFERENCES users,action text NOT NULL,data jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX activity_page ON activity(workspace_id,id DESC);
CREATE INDEX activity_project ON activity(workspace_id,project_id,id DESC);
CREATE TABLE notifications(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,workspace_id uuid NOT NULL,user_id uuid NOT NULL,title text NOT NULL,issue_id uuid,read_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(workspace_id,user_id) REFERENCES members ON DELETE CASCADE);
CREATE INDEX notifications_page ON notifications(user_id,workspace_id,id DESC);
CREATE INDEX notifications_unread ON notifications(user_id,workspace_id) WHERE read_at IS NULL;
CREATE TABLE events(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,workspace_id uuid NOT NULL REFERENCES workspaces ON DELETE CASCADE,kind text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX events_cursor ON events(workspace_id,id);
